name: Deploy

on:
  pull_request: { branches: master }
  push: { branches: master }


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./utils
        
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'bloggql' #Must be unique in Heroku
          heroku_email: 'gui.lefort.17@gmail.com'

